import type { Metadata } from "next";



import "../globals.css"
import SubHeader from "@/components/SubHeader";
import { ClerkProvider } from '@clerk/nextjs'
import Header from "@/components/Header";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Roboto } from "next/font/google";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: ['400', "500", "700", "900"],
  subsets: ['latin'],
  style: ['normal'],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={roboto.className}>
        <SubHeader />
        <Header />
        {children}
        <SpeedInsights />
  
      </body>
    </html>
    </ClerkProvider>
  );
}
