import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"

import 'bootstrap/dist/css/bootstrap.min.css';
import "../globals.css"
import SubHeader from "@/components/SubHeader";
import { ClerkProvider, auth } from '@clerk/nextjs'
import Header from "@/components/Header";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Roboto } from "next/font/google";
import { getCartTotalCount, getUserById } from "@/lib/actions/cart.actions";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: ['400', "500", "700", "900"],
  subsets: ['latin'],
  style: ['normal'],
})


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth()
    
  const user = await getUserById({clerkId:userId!})
 
   const qty = await getCartTotalCount({
     userId: user?.user?._id
   })
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={roboto.className}>
        <SubHeader />
        <Header qty={qty} user={user} />
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
    </ClerkProvider>
  );
}
