import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import "../globals.css"
import SubHeader from "@/components/SubHeader";
import { ClerkProvider } from '@clerk/nextjs'
import Header from "@/components/Header";
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <SubHeader />
        <Header />
        {children}
        <SpeedInsights />
   <ToastContainer theme="dark" />
      </body>
    </html>
    </ClerkProvider>
  );
}
