import type { Metadata } from "next";
import { Roboto,  } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";




const roboto = Roboto({
  weight: ['400', "500", "700", "900"],
  subsets: ['latin'],
  style: ['normal'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       
        {children}
      </body>
    </html>
  );
}
